### ISSUE TITLE
CUSP calculates incorrect number of connected components

### ISSUE THREAD

**Issue by DhariniCool** [cusplibrary/cusplibrary#72]
Hi, 

I am trying to use cusp to calculate the number of connected components in large graphs. I am using csr file format to read matrix market graph files. I have encountered the following issues.

**Issue 1:** CUSP outputs different(no. of components) results when I run the code with same dataset on different runs. 

Run1 : command: ./cusp_cc_mtx in-2004.mtx 
Output: Connected Components - [CUSP]
Input filename - in-2004.mtx
Number of Connected Components : 542

Run2 : command: ./cusp_cc_mtx in-2004.mtx 
output: Connected Components - [CUSP]
Input filename - in-2004.mtx
Number of Connected Components : 526

Run3 : command: ./cusp_cc_mtx in-2004.mtx 
output: Connected Components - [CUSP]
Input filename - in-2004.mtx
Number of Connected Components : 519

None of the above calculated number of connected components is correct. The actual number of components for the above mentioned dataset is 134 which I verified it with a serial code. I re-ran it for different datasets and faced the same issue.

**Issue 2:** For some matrix market graphs, I am not able to run cusp. I get the following error,

"[/home/jayadharini/cusp/cusplibrary-0.5.1/cusp/system/cuda/detail/graph/b40c/graph/bfs/enactor_hybrid.cuh, 538] Frontier queue overflow.  Please increase queue-sizing factor.  (CUDA error 9: invalid configuration argument)"

Is there any limit on the input dataset's size?  I ran the cusp code for various datasets and I noticed that I get this error for datasets with large number of connected components. I am able to run it for larger datasets with less number of connected components. Please clarify!

I am using,
CUDA   v7.5
Thrust v1.8
Cusp   v0.5

I also tried using cusp - 5.1 and the current development version in github. I am compiling with sm_30. Since I am a student working on university server, I cannot upgrade to CUDA 8.0.

Please help me fix this.

Thanks,
Dharini

**Comment by et22** [comment]
I have the exact same problem. 

The connected components algorithm does not output the correct number of connected components.
