### ISSUE TITLE
CUDA9.0 Compatibility 

### ISSUE THREAD

**Issue by sdalton1** [cusplibrary/cusplibrary#80]
Add limited support for Thrust version that ships with CUDA 9.0. Support will be limited because there is a bug in the Thrust version that ships with CUDA 9.0 related to https://github.com/thrust/thrust/issues/635.

Need a way to reconcile the differences between the Thrust version on Github and the version that ships with CUDA 9.0.

**Comment by jfeist** [comment]
Has there been any progress on this?

**Comment by sdalton1** [comment]
I added a CUDA 9.0 compatibility branch that addresses some of the compilation issues. Unfortunately, the only way to fix the template error in the Thrust version that ships with CUDA 9.0 is to apply a patch until CUDA 9.1 is released. I will try uploading the patch here for reference.

**Comment by jfeist** [comment]
Thanks for the info - I hadn't realized that there was a branch for cuda9. I haven't tried running anything yet, so I'm not sure if I'll run into the bug, but with this I could at least compile PETSc with CUDA support (which failed with the released version).
