### ISSUE TITLE
Performance calculation of spmv using csr_blocked

### ISSUE THREAD

**Issue by KhalidTheeb** [cusplibrary/cusplibrary#89]
In file [cusplibrary/performance/spmv/benchmark.h](https://github.com/cusplibrary/cusplibrary/blob/develop/performance/spmv/benchmark.h) you are using two different equations to compute spmv performance:

The general method in function _test_spmv_ line 171:
_`float GFLOPs = (time == 0) ? 0 : (2 * host_matrix.num_entries / time) / 1e9;`_ //equation (1)

 And then in function _test_spmv_block_ line 198:
 _`float GFLOPs = (time == 0) ? 0 : (num_cols * 2 * host_matrix.num_entries / time) / 1e9;`_ //equation (2)

I am wondering why num_cols is multiplied by 2NNZ in the blocked version, even though the number of spmv operations are the same as any other storage format that uses the first equation.

**Comment by sdalton1** [comment]
Blocking in that test refers to operations with multiple dense right-hand side vectors, not blocking in the CSR format. Sorry for the confusion in the naming.
